service:
  name: zombie-chat-be-broadcaster

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: ${env:STAGE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ConnectionTable, Arn]
  environment:
    CONNECTION_TABLE_NAME: ${env:CONNECTION_TABLE_NAME}

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: # enable auto-packing of external modules
      forceExclude:
        - aws-sdk

functions:
  connect:
    handler: src/handler.connect
    timeout: 12
    memorySize: 256
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/handler.disconnect
    timeout: 12
    memorySize: 256
    events:
      - websocket:
          route: $disconnect
  broadcast:
    handler: src/handler.broadcast
    timeout: 6
    memorySize: 128
    events:
      - websocket:
          route: $default

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:CONNECTION_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
